safe: true
exclude:
  - /embedded
  - /scripts
  - /.env
  - /compile
  - /flash
  - /README.md
  - /vendor
motlurl: http://www.meetup.com/Make-on-the-Lake/

baseurl: /teddy-bear-workshop
repourl: https://github.com/make-on-the-lake/teddy-bear-workshop
workshop_name: Teddy Bear Workshop
gaq_id:
