#!/usr/bin/env bash

cd "$(dirname "$0")/embedded"

./../scripts/check-dependencies || { exit 1; }

particle setup

echo ""
echo "Now remind me again..."
echo "What did you name your core again?"
until read -r name 2>/dev/null; do :; done
echo ""

particle flash $name ./teddy
